
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by wsdl2js tool.
//     Runtime Version: 0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
	//remote web server request object
	var xmlHttpRequest;
	function getHttpRequest(){
		var http_request;
		if (window.XMLHttpRequest) { // Mozilla, Safari, ...
			 http_request = new XMLHttpRequest();
		}else if (window.ActiveXObject) { // IE
			 http_request = new ActiveXObject("Microsoft.XMLHTTP");
		 }else{
			 alert("Your browser doesn't support to create XMLHttp Object,Some content on this page can't show.");
			 return null;
		}
		 return http_request;
	}

	// define a class to encapsulate invoking of web service
	// the class name is the name of web service
	// url -  location of access web service.
	function ServiceInfo(url){
		// url=http://192.168.188.70:8038/wsgs/services/ServiceInfo
		this.url = url
		this.request1=request1
		this.request=request
	}


	// web service method
	function request1(/*int*/ in0,/*base64Binary*/ in1) {
		soapMess ="<?xml version=\"1.0\" encoding=\"utf-8\"?>"
		+"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
		+"<soap:Body>"
		+"<request1 xmlns=\"http://inf.sz.kingyi.com\">"
		soapMess += "<in0>"+in0+"</in0>"
		soapMess += "<in1>"+in1+"</in1>"
		soapMess +="</request1>"
		soapMess +="</soap:Body></soap:Envelope>"
		xmlHttpRequest = getHttpRequest()
		xmlHttpRequest.onreadystatechange = request1_callback
		xmlHttpRequest.open("POST",this.url,true);
		xmlHttpRequest.setRequestHeader("SOAPAction","");
		xmlHttpRequest.setRequestHeader("Content-Type","text/xml; charset=utf-8");
		xmlHttpRequest.send(soapMess);
	}

	// this function will be called when result return from web service.
	function request1_callback(){
	// return value from web service is an xml document.
		var rawData;
		if (xmlHttpRequest.readyState == 4){
			if (xmlHttpRequest.status == 200){
				rawdata = xmlHttpRequest.responseXML;
				var resultNode = rawdata.documentElement.firstChild.firstChild.firstChild;
				var resultValue = resultNode
				// Now,you can process the returnValue in function request1_handler
				request1_handler(resultValue);
			}else{
				alert("web service response error:" + xmlHttpRequest.status + "," + xmlHttpRequest.statusText);
			}
		}
	}

	// process result value of method request1
	function request1_handler(/*base64Binary*/ resultValue) {

	}



	// web service method
	function request(/*string*/ in0) {
		soapMess ="<?xml version=\"1.0\" encoding=\"utf-8\"?>"
		+"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
		+"<soap:Body>"
		+"<request xmlns=\"http://inf.sz.kingyi.com\">"
		soapMess += "<in0>"+in0+"</in0>"
		soapMess +="</request>"
		soapMess +="</soap:Body></soap:Envelope>"
		xmlHttpRequest = getHttpRequest()
		xmlHttpRequest.onreadystatechange = request_callback
		xmlHttpRequest.open("POST",this.url,true);
		xmlHttpRequest.setRequestHeader("SOAPAction","");
		xmlHttpRequest.setRequestHeader("Content-Type","text/xml; charset=utf-8");
		xmlHttpRequest.send(soapMess);
	}

	// this function will be called when result return from web service.
	function request_callback(){
	// return value from web service is an xml document.
		var rawData;
		if (xmlHttpRequest.readyState == 4){
			if (xmlHttpRequest.status == 200){
				rawdata = xmlHttpRequest.responseXML;
				var resultNode = rawdata.documentElement.firstChild.firstChild.firstChild;
				var resultValue = resultNode.firstChild.nodeValue
				// Now,you can process the returnValue in function request_handler
				request_handler(resultValue);
			}else{
				alert("web service response error:" + xmlHttpRequest.status + "," + xmlHttpRequest.statusText);
			}
		}
	}

	// process result value of method request
	function request_handler(/*string*/ resultValue) {

	}



